### ISSUE TITLE
AssertionError: the sparsity pattern of A must include diagonal elements

### ISSUE THREAD

**Issue by Viech** [cvxopt/smcp#12]
Hello again,

we triggered an assertion failure within CHOMPACK with the following script and another SDP. I don't know if the issue is in SMCP or CHOMPACK. Script and pickled problem data are found at http://dl.viech.name/picos_issue_206.zip as I once more cannot attach either the files nor the archive. MD5 checksums are:
```
7adaf606092a591055031a16646bbf4f  picos_issue_206.zip
6785b7f1da5cdb4bbc5bc00bee57d07c  picos_issue_206.pickle
e9b66185d4b3b4069a84cbe9ad79f45e  picos_issue_206.py
```
The issue is tracked on PICOS end in https://gitlab.com/picos-api/picos/issues/206 and can also be reproduced by checking out the `nuclearnorm` branch and running `./test.py -s smcp -c HERMITIAN_NUCLEAR_NORM -k`.

Script:
```python
#!/usr/bin/python

import pickle
from sys import version

import chompack
import smcp

with open("picos_issue_206.pickle", "rb") as f:
    c, G, h, dims = pickle.load(f)

print("Python", version.splitlines()[0])
print("CHOMPACK", chompack.__version__)
print("SMCP", smcp.__version__)
print()
print("c", repr(c))
print("G", repr(G))
print("h", repr(h))
print("dims", dims)
print()

smcp.solvers.conelp(c, G, h, dims)
```
Output:
```
Python 3.8.1 (default, Jan 22 2020, 06:38:00) 
CHOMPACK 2.3.3
SMCP 0.4.6

c <28x1 matrix, tc='d'>
G <121x28 sparse matrix, tc='d', nnz=169>
h <121x1 matrix, tc='d'>
dims {'l': 49, 'q': [], 's': [6, 6]}

Traceback (most recent call last):
  File "./picos_issue_206.py", line 22, in <module>
    smcp.solvers.conelp(c, G, h, dims)
  File "/usr/lib/python3.8/site-packages/smcp/solvers.py", line 2368, in conelp
    sol = P.solve_esd(kktsolver=kktsolver)
  File "/usr/lib/python3.8/site-packages/smcp/base.py", line 260, in solve_esd
    return solvers.chordalsolver_esd(self.A,self.b,kktsolver=kktsolver,\
  File "/usr/lib/python3.8/site-packages/smcp/solvers.py", line 1464, in chordalsolver_esd
    symb = symbolic(Va,p)
  File "/usr/lib/python3.8/site-packages/chompack/symbolic.py", line 537, in __init__
    assert len([i for i,j in zip(Ap.I,Ap.J) if i==j]) == A.size[0], "the sparsity pattern of A must include diagonal elements" 
AssertionError: the sparsity pattern of A must include diagonal elements
```
The problem is successfully solved with both CVXOPT and MOSEK, so it should not be illposed.

**Comment by martinandersen** [comment]
It violates the assumption made in SMCP that all diagonal elements are included in the sparsity pattern (see [documentation](https://smcp.readthedocs.io/en/latest/documentation/index.html)). Specifically, if you have an LMI of the form 

    sum_k A_k*y_k + S = C

where the data matrices C, A_1,...A_m have a diagonal zero in common (say, the i'th diagonal element), then the corresponding row/column of S must zero in order for S to be p.s.d. and feasible. This means that you can  reduce the size of the problem by deleting a row/column from S.

**Comment by Viech** [comment]
OK, so we shall preprocess the input like this. (Though, @gsagnol, do you see how this is even possible with your nuclear norm reformulation? From what I see, all LMI diagonal elements in the resulting problem should be variables. Let's discuss this later.)

Nitpick: CHOMPACK needs to raise a `ValueError` instead; an assertion failure implies that there is a bug in the software and that it is _not_ a user error.

Thank you for your time again.
