### ISSUE TITLE
What is the argument type of the parameter "h" of conelp?

### ISSUE THREAD

**Issue by Viech** [cvxopt/smcp#2]
Hello, I'm using SMCP 0.4.3. The [documentation](http://smcp.readthedocs.io/en/latest/documentation/index.html#smcp.solvers.conelp) says about `conelp` (which has an argument `h`) nothing more than that it is an interface to `chordalsolver_esd` (which does not have an argument `h`), so the type and meaning of the argument `h` is not immediately clear. Since `lp`, `socp` and `sdp` are said to be interfaces to `conelp` that also take an argument `h`, I considered their documention instead, which in turn is a redirect to the [CVXOPT documentation of the corresponding functions](http://cvxopt.org/userguide/coneprog.html). There, the types are explicitly given:

- For `cvxopt.solvers.conelp`:
  > The arguments c, h, and b are real single-column dense matrices.
- For `cvxopt.solvers.lp`:
  > The meaning of the other arguments and the return value are the same as for conelp called with dims equal to {'l': G.size[0], 'q': [], 's': []}.
- For `cvxopt.solvers.socp`:
  > hl is a real single-column dense matrix.
- For `cvxopt.solvers.sdp`:
  > hl is a real single-column dense matrix. […] Gs and hs are lists of length N that specify the linear matrix inequality constraints.

However, when I supply `h` in the form of a `cvxopt.matrix` (as I would do with `cvxopt.solvers.conelp`), I get the following exception:

    […]
      File "/usr/lib/python3.6/site-packages/smcp/solvers.py", line 2335, in conelp
        v = h.spmatrix(reordered=False, symmetric=False)
    AttributeError: 'cvxopt.base.matrix' object has no attribute 'spmatrix'

Hence the question: What is the type of the `h` argument of `smcp.solvers.conelp`?

**Comment by martinandersen** [comment]
Thanks for reporting this—it's a bug that was introduced when we switched from Chompack 1.x to Chompack 2.x. The input h should indeed be a cvxopt.matrix or cvxopt.spmatrix. It has been fixed in 28a69e6cbeb8309110e058caf69be2d3f717b0d4.
